# Generated by Django 3.2.8 on 2021-10-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_zad_rek', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='URL',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
